# Site settings
theme: jekyll-theme-minimal
classes: wide 
toc: true
title: <b>Work Plans</b>
logo: /assets/Home.png
description: <h2>Event Plan</h2>
	<p>Monday 10:00-12:00</p>
             <p><a href="https://us02web.zoom.us/meeting/register/tZctdOyhqT4tH9DubmQ3qKwI8_s1lxkQ4xhx">Registration Form</a></p>
show_downloads: false
footer: false

       

