# Site settings
theme: jekyll-theme-minimal
classes: wide 
title: <b>Work Plans</b>
logo: /assets/Home.png
description: <h2><strong>Event Plan</strong></h2><br>
		<a href="#CESSDA Training Activities 2020">CESSDA Training Activities 2020</a><br>
		<a href="#CESSDA Trust Support 2020">CESSDA Trust Support 2020 </a><br>
		<a href="#CESSDA Metadata Office: Metadata Model"> CESSDA Metadata Office Metadata Model</a><br>
		<a href="#CESSDA Metadata Office: ELSST, CVS and CDC"> CESSDA Metadata Office ELSST, CVS and CDC </a><br>
		<a href="#CESSDA Ontology Management System">CESSDA Ontology Management System</a><br>
		<a href="#CESSDA Vocabulary Service Maintenance 2020">CESSDA Vocabulary Service Maintenance 2020 </a><br>
		<a href="#CESSDA Euro Question Bank 2020"> CESSDA Euro Question Bank 2020 </a><br>
		<a href="#CESSDA Widening Activities and Journal Outreach 2020">CESSDA Widening Activities and Journal Outreach 2020 </a><br>
		<a href="#New Data Types 2020"> New Data Types 2020 </a><br>
             <a href="https://us02web.zoom.us/meeting/register/tZctdOyhqT4tH9DubmQ3qKwI8_s1lxkQ4xhx">Registration Form</a><br>
show_downloads: false
footer: false

       

