# Site settings
layout: default
title: Work Plans
logo: /assets/Home.png
description: DATE
toc: true
toc_label: "Table of Contents"
toc_icon: "cog"
toc_sticky: true
show_downloads: false
theme: jekyll-theme-minimal
