# Site settings
theme: jekyll-theme-minimal
layout: default
title: Work Plans
sidebar: true
toc: true
toc_label: "Table of Contents"
logo: /assets/Home.png
description: <p>Event Plan</p>
             <p>Monday 10:00 - describtion</p>
             <p>Tuesday 10:00 - describtion</p>
             <p>Wednseday 10:00 - describtion</p>
             <a href="https://us02web.zoom.us/meeting/register/tZctdOyhqT4tH9DubmQ3qKwI8_s1lxkQ4xhx">Registration Form</a>
show_downloads: false

